### PR TITLE
Funguar s mixin

### PR DESCRIPTION
**Pull request by MowFord**
Holding until `setStealItem` merges and spicy completes retail verification of behavior

### CODE REVIEW

**Comment by MowFord** [comment]
@Spicyryan fyi

need to confirm animation sub changes when successfully stealing from WoTG funguar (and perhaps confirm it _doesn't_ change in places like crawler's nest, but fairly sure it doesn't)

Also need to confirm regen during water weather

**Comment by Spicyryan** [comment]
> Also need to confirm regen during water weather

Slug study PTSD intensifies..

**Comment by Spicyryan** [comment]
> > Also need to confirm regen during water weather
> 
> Slug study PTSD intensifies..

image

Level 49 Coppercap in Rolanberry (S) has ~2,400 HP, every 6-9 seconds it gains 1%. This puts it at what seems like same value as the Slug family, 10 HP/tick.

There shall now be a really random nice page on BG now:
https://www.bg-wiki.com/ffxi/Coppercap

Also updated the family page with the auto-regen.
https://www.bg-wiki.com/ffxi/Category:Funguar

**Comment by Spicyryan** [comment]
image

**Comment by Spicyryan** [comment]
image

**Comment by Spicyryan** [comment]
Despoil does not change the mushroom like steal or the right TP move:
image

**Comment by Spicyryan** [comment]
image

**Comment by Spicyryan** [comment]
image

**Comment by Spicyryan** [comment]
Came back to check out of curiosity. The mushrooms do not respawn either after being idle for awhile:
image

**Comment by MowFord** [comment]
https://github.com/LandSandBoat/server/pull/5788

**Pull request closed without merging**
